# Site settings
title: Android Junior Developer
email: android@mindic.com
description: "All you need to know to get a job as an Android Junior Developer in one practicas course"
url: "http://android.mindic.com"
twitter_username: mindicom


#mixpanel_dev_token: "18af4642364437ebc4a717819c6e0aec"
#mixpanel_prod_token: "d5e14496868d0a34f5d90b8701866cd0"

github_username:  jomargo

# Build settings
markdown: kramdown
permalink: pretty
baseurl: ""
include: ["_fonts", "_bg_videos"]

gems:
  - jekyll-sitemap
  - jekyll-redirect-from

sass:
  sass_dir: _sass